CREATE TABLE `USUARIO` (
	`ID` bigint NOT NULL AUTO_INCREMENT,
	`NOME` varchar(255) NOT NULL,
	`EMAIL` varchar(255) NOT NULL UNIQUE,
	`SENHA` varchar(255) NOT NULL,
	`TELEFONE` char(11) NOT NULL UNIQUE,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `POST` (
	`ID` bigint NOT NULL AUTO_INCREMENT,
	`USUARIO_ID` bigint NOT NULL,
	`TITULO` varchar(255) NOT NULL,
	`DESCRICAO` varchar(255) NOT NULL,
	`MIDIA` varchar(255) NOT NULL,
	`META` DECIMAL(255) NOT NULL,
	`LOCALIZACAO` varchar(255) NOT NULL,
	`DATA` DATE(255) NOT NULL,
	`DOADO` DECIMAL NOT NULL,
	`DOADOR` varchar(255) NOT NULL,
	`COMENTARIO` varchar(255) NOT NULL,
	`CATEGORIA` bigint(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

CREATE TABLE `CATEGORIA` (
	`ID` bigint NOT NULL AUTO_INCREMENT,
	`TEMA` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`)
);

ALTER TABLE `POST` ADD CONSTRAINT `POST_fk0` FOREIGN KEY (`USUARIO_ID`) REFERENCES `USUARIO`(`ID`);

ALTER TABLE `POST` ADD CONSTRAINT `POST_fk1` FOREIGN KEY (`CATEGORIA`) REFERENCES `CATEGORIA`(`ID`);

